---
- descriptor: "pip-services-commons:logger:console:*"
  level: "trace"

- descriptor: "pip-services-dummies:controller:*:*"
  message: "Hello from dummy controller #1"

- type: "DummyController,test.DummyController"
  message: "Hello from dummy controller #2"
